### ISSUE TITLE
Any suggestions for Glyph type lib key?

### ISSUE THREAD

**Issue by typoman** [unified-font-object/ufo-spec#107]
I use the glyph type 'mark' or 'base' for two reasons:

1. To adjust the metrics of an accented glyph which is a composite.
2. To generate GDEF table for OT features.

To guess the glyph type there are many ways. For example, if I want to fix a composite metric, if a component is a mark/diacritic I ignore it and if a component is a base, I take the composite width from the base glyph. This requires guessing if a component base glyph Unicode is a mark or if the glyph has mark anchors or its width is zero, then I know it's a mark.

I was thinking of adding a glyph lib key `glyphtype` but I don't know if the key should be prefixed with a `public` or anything. What would be an appropriate key for holding this information? The glyph types can be `mark`, `base`, `component`, `ligature` [(OpenType Feature File Specification)](https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#9b-gdef-table)

Thanks!

**Comment by justvanrossum** [comment]
If it's for your own tool to use, then a key with a reverse domain name is appropriate, for example: `design.bahman.glyphtype`. 

For a `public.` prefix it needs to become part of the spec.

(I don't know exactly how ufo2ft generates `GDEF`, but it somehow manages without that information.)

**Comment by justvanrossum** [comment]
http://unifiedfontobject.org/versions/ufo3/conventions/#reverse-domain-naming-schemes

**Comment by typoman** [comment]
Thank you Just. I will just use the reverse domain name for now.

**Comment by anthrotype** [comment]
> I don't know exactly how ufo2ft generates GDEF

it doesn't. glyphsLib auto-generates a GDEF using predefined glyph names that are looked up in the GlyphData.xml database.
ufo2ft markFeatureWriter simply uses the GDEF table if one is defined in features.fea, and takes the glyph class definitions in there at face value.

**Comment by anthrotype** [comment]
if no explicit GDEF table is defined in the UFO features.fea, ufo2ft will (somewhat greedily) treat as a "mark" glyph any glyph that has a `_` prefixed anchor; a "base" glyph, any glyph that has an anchor that attaches to some other existing mark anchor; as "ligature" any glyph that has more than 1 attaching anchors with the same name but different suffixes "top_1", "top_2".

fonttools feaLib will auto-generate a GDEF table (as mandated by the Adobe FEA spec) by inferring the GDEF glyph classes from the way glyphs are used in GPOS mark/mkmk lookups.

**Comment by typoman** [comment]
> fonttools feaLib will auto-generate a GDEF table (as mandated by the Adobe FEA spec) by inferring the GDEF glyph classes from the way glyphs are used in GPOS mark/mkmk lookups.

Does this mean if there is a glyph being defined in a mark class, or attached to a base, then it doesn't have to be defined as a mark in GDEF again, it's already defined as a mark in GDEF by fealib compiler?

**Comment by anthrotype** [comment]
feaLib will only try to infer GDEF glyph classes if the user did not provide explicit definitions in the features.fea.

**Comment by anthrotype** [comment]
so you either go fully manual and define your GDEF classes (and anything which is left out will be ignored by both ufo2ft markFeatureWriter or feaLib compiler), or you let your glyph classifications be inferred from they presence of anchors and the usage of glyphs as marks/base/ligatures in mark/mkmk lookups. Depending on your setup you may want greater control, or you may be happy with the automatically generated/inferred classes.

**Comment by typoman** [comment]
Thank you Cosimo for explaining this, that's a very nice mechanism. Now I can see how to use this in my workflow.
