### ISSUE TITLE
openTypeOS2WeightClass should be "in sync" with postscriptWeightName, but this is impossible

### ISSUE THREAD

**Issue by ctrlcctrlv** [unified-font-object/ufo-spec#111]
Greetings from the @FontForge project.

The spec defines:

Name | Type | Description
-- | -- | --
postscriptWeightName | string | A string indicating the overall weight of the font. This corresponds to the Type 1/CFF Weight field. It should be in sync with the `openTypeOS2WeightClass` value.
openTypeOS2WeightClass | non-negative integer | Weight class value. Corresponds to the OpenType OS/2 table `usWeightClass` field.

This seems to require that a string be "in sync" with an integer, which seems impossible.

The only way I can think of to force this to make sense is to say that in UFO fonts, the CFF `/Weight` must be represented as a string representation of the integer OS/2 weight class. There is no standard string representation of the OS/2 weight classes, or even some of them (see https://github.com/probonopd/font-leutkirch/issues/11#issuecomment-623149694 &sect; Q12), so there is no other possible meaning.

But most real world fonts don't have integers in CFF `/Weight`. Page 11 of the [Type 1 Specification](https://www.adobe.com/content/dam/acom/en/devnet/font/pdfs/T1_SPEC.pdf) has an example CFF `/Weight` of "Medium".

So, who is wrong? Adobe or UFO? :-)

**Comment by benkiel** [comment]
@ctrlcctrlv I think you are reading "in sync" to be more literal than the meaning here. It means that the `postscriptWeightName` should be related to the `openTypeOS2WeightClass`, i.e. value of `400` for `openTypeOS2WeightClass` would mean that `postscriptWeightName` would be `Regular` or `Book`, not `Ultra`, `Black`, etc. 

The `postscriptWeightName` should be a string, not a string representation of an integer. The only standard mapping for this is given by the OT spec (https://docs.microsoft.com/en-us/typography/opentype/spec/os2#usweightclass), but these have multiple options and do not cover things that are between the hundred values. So it's rather up to an authoring tool or designer to come up with these names.

Again, "in sync" means "is reasonable for the usWeightClass value" and note that the spec has this as `should` not `must`.

If you have better wording here, please feel free to open a PR.

**Comment by ctrlcctrlv** [comment]
I'd go with "should have a reasonable value vis à vis openTypeOS2WeightClass, e.g. "Medium" for 500."

**Comment by ctrlcctrlv** [comment]
Thank you @benkiel&mdash;I was about to open a PR complaining that this had been prematurely closed, but saw that you committed https://github.com/unified-font-object/ufo-spec/commit/1b508160e1ba69c77d471ab9ba1ea37c686264d1.
