### ISSUE TITLE
The UFO website sucks.

### ISSUE THREAD

**Issue by typesupply** [unified-font-object/ufo-spec#119]
The current site was designed by me 15 or so years ago and it was terrible even then. We should redesign it to 2005+ standards and capabilities.

**Comment by belluzj** [comment]
To be honest it's not that bad, it works well as reference document to visit once in a while and Ctrl-F for the definition of some field. And at least it exists and is online today, which is great already. The design looks fine to me in the sense that it's practical.

**Comment by colinmford** [comment]
I also don't have a problem with it

**Comment by typesupply** [comment]
Update: I'm working on new CSS. With @belluzj mini-spec section and other stuff that needs to be added, it's a good time to fix my mess.

**Comment by belluzj** [comment]
I rebased my PR #124 on top of the new design: https://daltonmaag.github.io/ufo-spec/extensions/lib_and_data/
