### ISSUE TITLE
Caret-like anchors

### ISSUE THREAD

**Issue by khaledhosny** [unified-font-object/ufo-spec#120]
OpenType has several data structure that specify only `x` (or `y`) position, the most famous is GDEF ligature carets, but there are also italic correction and top accent position in MATH table.

Glyphs (ab)uses anchors for this, and some plugins interpret specific anchor names to draw a line at `x` position and ignore the `y` position. I think there should be a more explicit way to store such data.

**Comment by benkiel** [comment]
See also #32  and #91

**Comment by khaledhosny** [comment]
Oh, I forgot about #91. Closing then.

**Comment by benkiel** [comment]
@khaledhosny no worries, it's hard to keep track!
