### ISSUE TITLE
Question: how do I build the docs locally for development?

### ISSUE THREAD

**Issue by arrowtype** [unified-font-object/ufo-spec#133]
I have noticed a couple of tiny CSS issues I’d like to submit PRs for, but I am unsure of how to build this site locally.

I think this is probably a Jekll site, but ideally there might be an explanation in the readme (and also potentially a `package.json` file) to help contributors install dependencies and build the site locally in order to test changes and potentially submit PRs.

Thanks for the amazing upgrade to the docs, Tal!

**Comment by typesupply** [comment]
I'm 1000% unqualified to explain anything web + ruby related, but this is what I do:

- cd to the directory containing the `_config.yml` file.
- in `_config.yml` change `baseurl: "/"` to `baseurl: ""`. *
- In Terminal: `bundle exec jekyll serve`.
- Use Netscape Navigator (v 2.1a3) to browse to localhost:4000.

*For some reason that I do not understand, if this is `"/"` when run locally, the CSS doesn't load. It made me very frustrated for a very long time.

**Comment by arrowtype** [comment]
Thanks!

When I use `bundle exec jekyll serve`, I get the follower error:

```console
Could not locate Gemfile or .bundle/ directory
```

I think this is likely because `Gemfile` is in the `.gitignore`, while it should be in the root directory. Is there a reason not to commit it, or would you be willing to add it in?

**Comment by typesupply** [comment]
That's probably something I did in desperation. I just removed it from .gitignore and pushed it. Fingers crossed.

**Comment by arrowtype** [comment]
Awesome, thanks! That works for me. 

I’m not sure if there is a good place to add this info, but the process seems to be:

1. Install ruby gems and bundler ([how to](https://idratherbewriting.com/jekylldoctheme-separate-outputs/mydoc/mydoc_install_dependencies.html))
3. `bundle install` (I had to add `sudo` before it, but maybe shouldn’t have)
4. `bundle exec jekyll serve`
