### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by arrowtype** [unified-font-object/ufo-spec#141]
I think either a simple `U` or the `*` adapted from the header could work well:

![image](https://user-images.githubusercontent.com/45946693/90336515-5911e200-dfaa-11ea-8b5c-faeb5a3eea25.png)

Once we agree on an icon, we should use the favicon generator to make sure we can easily cover all the bases:

https://realfavicongenerator.net/

**Comment by benkiel** [comment]
The U.

**Comment by arrowtype** [comment]
Agreed. On it!
