### ISSUE TITLE
Lock guidelines individually

### ISSUE THREAD

**Issue by ryanbugden** [unified-font-object/ufo-spec#145]
I'm wondering if it'd be worth it to add a `locked` attribute to font or glyph guidelines on an individual basis. It would help in cases like [this](https://github.com/ryanbugden/RoboFont/tree/master/Glyph%20Beam%20Menu), where I would like for one guideline to be locked, and the others’ lock state to be user-decided, globally. Maybe the default would be something like `locked = 'inherit'`... in which case it would be controlled by the user's global guideline lock setting.

I see how this complicates things, but wanted to propose the idea, as guidelines have proven useful to me in more abstract [ways](https://github.com/ryanbugden/Edit-Font-Dimensions) than one might initially imagine.

**Comment by benkiel** [comment]
This would be a good case for the `lib`, each editor may do this differently.
