### ISSUE TITLE
Meaning of smooth attribute on move, line?

### ISSUE THREAD

**Issue by madig** [unified-font-object/ufo-spec#147]
According to the spec, `smooth` can be set on every point type except offcurves, but what would/should it mean on a `move` or `line` point?

**Comment by benkiel** [comment]
My understanding is that smooth on `line` or `move` are tangent points, meaning that there is one offcurve coming from that point, not two.

**Comment by justvanrossum** [comment]
A smooth flag on a `line` followed by an offcurve indicates a tangent. A `move` that's smooth doesn't seem to make much sense, but may still be useful once that contour gets closed. (It's useful to keep the smooth flag on a move that was previously a line or a curve, for when it gets reconnected to something else.)

A smooth flag on a line that's followed by a line makes no sense indeed, and perhaps the spec should say something about that.
