### ISSUE TITLE
Question/Feauture request for UFO4: GASP data

### ISSUE THREAD

**Issue by aminabedi68** [unified-font-object/ufo-spec#172]
Hi
I am an amateur font engineer working with ufo font format as the masters of variable fonts, so i'm not sure there is or not a way to include [gasp](https://docs.microsoft.com/en-us/typography/opentype/spec/gasp) data, if we can do it in ufo3 please show me how(sorry, i can't find relative data in documentations) and if this is not possible please add support in ufo4.

**Comment by moyogo** [comment]
UFO3 can represent gasp table data. See https://unifiedfontobject.org/versions/ufo3/fontinfo.plist/#opentype-gasp-table-fields and for example https://github.com/daltonmaag/ubuntu/blob/master/source/Ubuntu-R.ufo/fontinfo.plist#L52-L79

**Comment by aminabedi68** [comment]
Thank you @moyogo
