### ISSUE TITLE
the meaning of “may occur any number of times”

### ISSUE THREAD

**Issue by mbutterick** [unified-font-object/ufo-spec#179]
### ordered vs. unordered

It seems that the phrase “may occur any number of times” [is used](https://unifiedfontobject.org/versions/ufo3/glyphs/glif/) in two senses:

* to refer to **unordered** values: for instance, [`guideline`](https://unifiedfontobject.org/versions/ufo3/glyphs/glif/#guideline) and [`anchor`](https://unifiedfontobject.org/versions/ufo3/glyphs/glif/#guideline) values have no meaningful ordering (AFAICT).

* to refer to **ordered** values: for instance, [`point`](https://unifiedfontobject.org/versions/ufo3/glyphs/glif/#point) values have a meaningful order, and for [`unicode`](https://unifiedfontobject.org/versions/ufo3/glyphs/glif/#unicode) values, the first value is meaningful (= “primary Unicode value”).

Or if this surmise is incorrect — is it therefore always the case that values designated “may occur any number of times” also imply an order, which must be preserved (say, when writing out the UFO)?

### unique vs. not

If a value “may occur any number of times”, that means there might be repeated values. Is it always the case that the repetitions must be preserved?

Certainly, for something like `point` values, the answer is yes (leaving aside the fact that geometrically, repeated Bézier points may have no effect)

But consider `unicode` values. A glyph can contain zero or more of these. In every context I’m aware of, these should be understood as a **set** (that is, only unique occurrences count). But if one comes across something like this in a glif:

```
<unicode hex="0041" /> <unicode hex="0041" /> <unicode hex="0041" /> 
```

Is it fair to simplify this to 

```
<unicode hex="0041" />
```

Or not?

**Comment by benkiel** [comment]
@mbutterick it would be fair to collapse the repeated unicode values into one, yes. The spec should likely say that only one occurrence of a unicode value is valid.

As for ordered vs unordered, the spec is currently silent on this. I'll open an issue on it for debate.
