### ISSUE TITLE
Question about UTI declarations

### ISSUE THREAD

**Issue by timglorioso** [unified-font-object/ufo-spec#18]
The resource page lists the same declaration for both exported and imported types. [Apple's documentation](https://developer.apple.com/library/mac/documentation/FileManagement/Conceptual/understanding_utis/understand_utis_declare/understand_utis_declare.html#//apple_ref/doc/uid/TP40001319-CH204-SW3) states that exported UTIs are owned by the bundle's (application's) publisher, while imported UTIs are owned by another organization.

Since the resource page is for third parties, shouldn't it only include the imported declaration?

**Comment by benkiel** [comment]
Closing this, as the exported is there as a reference for a third party to build upon.
