### ISSUE TITLE
Add possibility to encode `single line fonts' (engraving/pen plotter/CNC fonts)

### ISSUE THREAD

**Issue by adaerr** [unified-font-object/ufo-spec#184]
I came across the UFO/GLIF format looking for a way to store a single line font as XML. This issue is possibly(probably?) completely outside the scope of the current UFO usage, so don't hesitate to close this right away if it doesn't deserve a thought.

Currently there are several formats for storing standard (outline) fonts, but AFAIK none with an open standard for encoding fonts that are made of open-ended single strokes (but again, I've barely touched this subject so I might have missed stuff). Existing single line fonts (Herschey, HP1345A, ...) each come in home-brewed custom formats that each require a custom parser. I wondered whether opening the GLIF format to these type of fonts could make them more accessible.

What I have done for my application is to create a `<stroke>` child to `<outline>` that is similar to `<contour>` but does not imply a closed path. To give an example, here's is the glyph "A" of the Hershey `romans` font:

```
<?xml version="1.0" encoding="utf-8"?>
<glyph name="LATIN CAPITAL LETTER A" version="0">
  <advance width="18" />
  <unicode hex="0041" />
  <note>
    <dict>
      <entry key="HerscheyGlyphNumber" type="DecimalUnsignedInteger">501</entry>
      <entry key="UnicodeName" type="Text">LATIN CAPITAL LETTER A</entry>
      <entry key="Character" type="Text">A</entry>
    </dict>
  </note>
  <anchor x="9" y="9" name="center" />
  <outline>
    <stroke>
      <point x="9" y="21" type="line" />
      <point x="1" y="0" type="line" />
    </stroke>
    <stroke>
      <point x="9" y="21" type="line" />
      <point x="17" y="0" type="line" />
    </stroke>
    <stroke>
      <point x="4" y="7" type="line" />
      <point x="14" y="7" type="line" />
    </stroke>
  </outline>
</glyph>
```

Of course I changed the file extension so there is no confusion with valid GLIF files, and can perfectly live with that for my project. I just opened this issue to create a discussion space in case there is some interest such an extension.

**Comment by benkiel** [comment]
@adaerr The UFO allows for open contours in glyphs, can you be more specific about what is blocking in the spec for encoding single line fonts?

**Comment by adaerr** [comment]
Oh, I have to read the standard again then :-P !

**Comment by adaerr** [comment]
My bad, it was right under my eyes, sorry for the noise then.

> When a contour does start with a move point, it signifies the beginning of an open contour.

(quoted from https://unifiedfontobject.org/versions/ufo3/glyphs/glif/#point-types )
