### ISSUE TITLE
Handling of symlinks in data dir?

### ISSUE THREAD

**Issue by madig** [unified-font-object/ufo-spec#188]
The [spec](https://unifiedfontobject.org/versions/ufo3/data/) says:

> The items within the directory may be either files or directories.

What about symlinks? I know this is very much a corner case. Imagine having a symlink point whereever and you write the UFO to a different place. Do you write out the symlink again or the bare file contents it points to? What if the symlink points to some internal glif file you delete and you write out the data dir again?

I'm inclined to error out on encountering a symlink...

**Comment by benkiel** [comment]
I would be inclined to agree with this, open to a PR for the spec
