### ISSUE TITLE
Float data type: should infinite, subnormal, and NaN be disallowed?

### ISSUE THREAD

**Issue by madig** [unified-font-object/ufo-spec#196]
The spec currently does not mention floating point corner cases like NaN where [floats](https://unifiedfontobject.org/versions/ufo3/conventions/#float) are involved (think e.g. contour point coordinates). Should they be disallowed? I can't think of a use-case...

**Comment by justvanrossum** [comment]
Probably.

**Comment by benkiel** [comment]
Contour points can be fractional in variable fonts, so I don't think that should be disallowed, you'd want those for intermediate masters, right?

**Comment by justvanrossum** [comment]
He's talking about float corner cases like NaN, not floats in general.

**Comment by benkiel** [comment]
Dur, sorry—too quick a read. Yes, agree disallow.
