### ISSUE TITLE
fontinfo 'postscriptBlueScale' and 'float' versus 'integer or float'

### ISSUE THREAD

**Issue by cmyr** [unified-font-object/ufo-spec#198]
Looking at the [docs for `fontinfo.plist`](https://unifiedfontobject.org/versions/ufo3/fontinfo.plist/#postscript-specific-data) in UFOv3, most types that can be floating-point numbers are listed as being *integer or float*s, with one exception: the 'postscriptBlueScale' field is described as a *float*.

My understanding is that 'integer or float' is essentially a detail of serialization: it allows the implementation to serialize an integer when the fractional part of a number is zero, which saves some space.

Given that understanding, I'm confused by the 'postcriptBlueScale' field. My best guess is that this is an oversight, but I wanted to make sure. Does anyone have any insight? Is there something special about this field?

**Comment by LettError** [comment]
https://stackoverflow.com/questions/8693290/what-does-bluescale-mean-for-type-1-fonts

**Comment by benkiel** [comment]
i.e. `postscriptBlueScale` will always be a float

**Comment by cmyr** [comment]
so to check my understanding, this value `x` is expected to be `0 < x < 1`?

**Comment by benkiel** [comment]
Yes. See also https://adobe-type-tools.github.io/font-tech-notes/pdfs/T1_SPEC.pdf section 5.6
