### ISSUE TITLE
Names for anchors, guidelines, points: require at least one character?

### ISSUE THREAD

**Issue by madig** [unified-font-object/ufo-spec#206]
The spec says about group and layer names that they must be at least one character in length. There is no minimum length for glyphs in contents.plist.md but in glif.md (oversight I presume, can send PR). There is however nothing specified for anchors, guidelines and point names. Should they have the same minimum length requirement applied?

**Comment by benkiel** [comment]
Yes. I can't think of a reason to have a name that is no length. If you could PR this it would be really welcome
