### ISSUE TITLE
Why versionMajor is "integer" but versionMinor "non-negative integer"?

### ISSUE THREAD

**Issue by anthrotype** [unified-font-object/ufo-spec#215]
Is there a reason why versionMajor is not defined as "non-negative" in the same way that versionMinor is?

![image](https://github.com/unified-font-object/ufo-spec/assets/6939968/98bd938c-2d2f-4023-aa0c-92ecd8e008bd)

I don't think a version can ever make any sense if it is negative, e.g. what does version -1.0 mean? Never seen one like that.

**Comment by twardoch** [comment]
"head.fontRevision" in the TT & OT specs is given as fixed type rather than ufixed. For this reason UFO speced this like so to be able to faithfully represent what might be in a font

**Comment by justvanrossum** [comment]
I'm not sure round-tripping a nonsensical value is a good enough reason. I for one would not be apposed to just change it to non-negative integer.
