### ISSUE TITLE
Some mechanism for sorting groups?

### ISSUE THREAD

**Issue by jenskutilek** [unified-font-object/ufo-spec#216]
In the source files I convert to UFO, groups are often sorted in a logical way (i.e. not alphabetically). As groups are stored in a dict inside the `groups.plist`, the sort order gets lost in the process, especially when the UFO is normalized.  That makes it very hard to work with the files (there's usually some hundreds of groups in the files I handle).

Maybe a lib key could be added which stores the preferred sort order of group names as an array?

```xml
<key>public.groupOrder</key>
<array>
  <string>myFirstGroup</string>
  <string>mySecondGroup</string>
  <string>myThirdGroup</string>
  <string>myFourthGroup</string>
</array>
```

**Comment by jenskutilek** [comment]
Or maybe the groups dict should be order-preserving during normalization?

**Comment by jenskutilek** [comment]
In [vfbLib](https://github.com/LucasFonts/vfbLib/tree/main), the group order is now written to a custom lib key so editors can restore the original order:

https://github.com/LucasFonts/vfbLib/blob/main/Lib/vfbLib/ufo/builder.py#L637-L639

**Comment by benkiel** [comment]
Hey @jenskutilek, apologies for missing this one. @typesupply, it feels too much for the spec to say 'must be an ordered dictionary', so maybe a public key is best here?

**Comment by typesupply** [comment]
Hmmm. Yeah, I think we would need to do a lib key.

**Comment by benkiel** [comment]
@jenskutilek If you want to do a PR for a public lib key, will accept!

**Comment by jenskutilek** [comment]
Finally came back to this. Could you take a look @benkiel?
