### ISSUE TITLE
Please mention the format of Boolean keys

### ISSUE THREAD

**Issue by mitradranirban** [unified-font-object/ufo-spec#229]
Please add description on how to represent a Boolean keys in the specifications as it is not mentioned specifically

**Comment by madig** [comment]
What kind of key do you have in mind? The plist format for lib keys has `<true/>` and `<false/>` elements.

**Comment by mitradranirban** [comment]
Thanks for your information. 
I want to manually set postscriptIsFixedPitch to true as my font editor Fontforge is failing to do so. But I could not find the syntax for doing so in the specs
