### ISSUE TITLE
Require features files to be self-contained

### ISSUE THREAD

**Issue by brawer** [unified-font-object/ufo-spec#23]
What would you think about adding the following to [features.html](http://unifiedfontobject.org/versions/ufo3/features.html)?

> If a feature file is present, it must be self-contained; for example, any glyph or mark classes must be defined within the file. If a client can interpret the feature file, its content takes precedence over kerning/groups.plist.

Currently, this is not clear from the spec, and this has caused a failure in our UFO-based font production pipeline. The following happened: A FontLab-to-UFO conversion tool had produced an UFO whose embedded feature file referred to glyph classes; these classes were not defined in the feature file, but only in groups.plist. Later in the pipeline, another tool tried compiling this feature file without modification, assuming it would be self-contained. See https://github.com/googlei18n/fontmake/issues/11.
- **Font production pipelines** can work on a defined semantics. If a feature file is present, the pipeline simply compiles it; no need to second-guess whether features.fea refers to outside constructs. If no feature file is present, the pipeline would of course use the UFO plists, just as today.
- **Naive editors** (who cannot decode feature files) can continue treating features.fea as an opaque blob. If a feature file is present and the editor leaves it untouched upon saving, any edits on kerning.plist would have no semantic impact. But this does not seem any worse than today, where the semantics is undefined.
- **Slightly ness naive editors** could do the following: When _writing_ UFO, it is easy to generate valid feature syntax for `feature kern` even for a naive implementation (or just omit the feature file altogether, if it has no other content than kerning). When _reading_ UFO, one can apply simple heuristics such as stripping off anything that  matches `feature kern {.*} kern;`. This is trivial to implement, but an import-export roundtrip would strip off any fancy kerning. However, advanced features like contextual kerning are rare; cannot be expressed in UFO anyway; and again, this seems better than an undefined semantics.
- **High-end editors** (who can decode feature files) would interpret `features.fea` when present, similar to font production pipelines.

**Comment by twardoch** [comment]
BTW: we **could** think of a minimal set of "decorators" (disguised as "special comments" a la the shell shebang) for FEA. We still have very few implementations of FEA processing (AFDKO, FontForge and feaLib). An "#!important" decorator or so could force a tool to give precedence to the FEA contents if it really contains hand-edited kerning (contextual etc.).

**Comment by benkiel** [comment]
A possibly naive question: this sounds like an issue with a certain workflow making an assumption that isn't something one can assume, not necessarily an issue with the UFO spec. Wouldn't it be better and less breaking to have the workflow not make this assumption?

**Comment by brawer** [comment]
Curious, how to convert UFO to OTF _without_ assuming that the features file is self-contained and takes precedence over conflicting information in *.plist?

**Comment by benkiel** [comment]
Sascha, let me run down my thinking on this:

The issue that you are having is that a tool in your workflow is making an assumption that the group data will be generated from the groups.plist & another tool in the workflow makes the assumption that the feature code is complete and doesn't generate group data from the groups.plist.

I don't think that this assumption that generating group data from the groups.plist is completely unreasonable but it does imply and possibly require that an application check any group definition in the features against the groups.plist to see if there is a conflict. This is an additional level of conflict resolution, from "Choose the features or choose the plist" to "Check the groups referred to in the features with the plist and deal with conflicts".

So, I would not be opposed to the first bit of your proposal, that "If a feature file is present, it must be self-contained; for example, any glyph or mark classes must be defined within the file" as this seems to be a reasonable requirement, would simplify conflict resolution, and would have informed the tool that wrote the kerning feature into your UFO that it also needed to write the groups into the feature.

However, I don't think that the second part —that the feature file takes precedence over the kerning/groups plist file— should be part of the specification. This is still an area for an application to sort out — it could (and in my experience is) very likely that the groups and kerning plist files are more up to date than the data in the features. One (be it a person or application) still has to make an explicit choice of what to do when confronted with both a kerning and groups plist and a kerning feature.

**Comment by brawer** [comment]
Thanks for the thoughtful reply; it makes total sense to me.

**Comment by brawer** [comment]
Sent you a pull request.

**Comment by typesupply** [comment]
I've given this some thought and I'm okay with the change as defined in the PR. This has always been a nasty issue to resolve and it's a large reason why we have a philosophy against data duplication. I'll apply your change to the new gh-pages branch. The master branch is going to go away so that the spec can be generated on the fly through GitHub Pages.

**Comment by typesupply** [comment]
@brawer One semi-related question: is roundtripping .fea -> feaLib -> .fea a lossless process? I'm sure whitespace changes, but are comments retained?

**Comment by behdad** [comment]
> @brawer One semi-related question: is roundtripping .fea -> feaLib -> .fea a lossless process? I'm sure whitespace changes, but are comments retained?

feaLib does not support exporting to .fea right now.  We plan to add that.  But if you are starting from GSUB/GPOS/GDEF, you definitely cannot get a lossless printout of the original .fea.

**Comment by typesupply** [comment]
Got it. Preserving the comments was always the most vexing problem when I tried to write .fea parsers.
