### ISSUE TITLE
Can the UFO 3 "images" directory contain subdirectories?

### ISSUE THREAD

**Issue by graphicore** [unified-font-object/ufo-spec#25]
The [spec](http://unifiedfontobject.org/versions/ufo3/images.html) is a bit ambiguous here stating:

> Each file must have a unique name but there are no file name requirements beyond making the file names file system appropriate.

Looking into ufoLib as the reference implementation, there are different implications by UFOReader and UFOWriter:

in [`UFOReader.getImageDirectoryListing`](https://github.com/unified-font-object/ufoLib/blob/master/Lib/ufoLib/__init__.py#L527) a subdirectory would be skipped, to be friendly to oldschool-SVN-(<= version 1.6)-like VCS:

``` py
        for fileName in os.listdir(path):
            p = os.path.join(path, fileName)
            if os.path.isdir(p):
                # silently skip this as version control
                # systems often have hidden directories
                continue
```

But, in the images handling methods in UFOWriter( `writeImage`, `removeImage`,  and `copyImageFromReader`) via `UFOWriter.writeBytesToPath`, `UFOWriter.removeFileForPath` and `UFOWriter.copyFromReader` writing images into subdirectories is  supported.

If we follow the _Zen of Python_:

> Flat is better than nested.

We could simplify UFOWriter a bit. However, to provide support for the `data` directory some of the subdirectory handling methods would still be needed. Also, a method of bringing order into the images dir would be lost.

The UFOReader reasoning of `#silently skip this as version control systems often have hidden directories` maybe needs to be reconsidered as well, because at least Subversion stopped putting an `.svn` directory into each sub directory since [realease 1.7 from 2011](https://subversion.apache.org/docs/release-notes/1.7.html#single-db) (support for 1.7 already ceased).

(offtopic:)

In general, I'd disallow alien directories within a UFO anyways. Even a `.git` directory in the root can easily cause trouble. The right way to do this is to put the whole UFO into a repository, instead of making the UFO itself the repository.

**Comment by typesupply** [comment]
Subdirectories aren't allowed. Yeah, UFOWriter should be changed. That's a mistake on my part.

**Comment by graphicore** [comment]
Thanks for the clarification.
