### ISSUE TITLE
Why are guideline angles CW?

### ISSUE THREAD

**Issue by adrientetar** [unified-font-object/ufo-spec#26]
Usual rotation direction is generally trigonometric in apps. I'm curious why clockwise angle was chosen.

**Comment by typesupply** [comment]
I don't recall. It may have been that the guide implementations that I referenced were predominantly clockwise. Too late to change it now. Can I close this issue?

**Comment by anthrotype** [comment]
hmm...
I think this very confusing. In elementary school we all learn that positive angles are measured with the initial side on the positive x axis, moving counter-clockwise around the origin.
Also Robofont guides work that way, not surprisingly.
Besides, the UFO3 spec only says: 

> in a clockwise direction from the horizontal

but does not specify whether it's the positive or negative x-axis. I assume it's the positive one, but that's not necessarily the case.
It would be nice if this issue could be addressed, at least in UFO4.

**Comment by anthrotype** [comment]
(actually, whether one starts measuring the angle from the positive or negative x-axis in clockwise direction, doesn't make any difference as the resulting guideline is the same..)

**Comment by typesupply** [comment]
I'm starting to think about changing it in UFO 3. There aren't a ton of implementations and guidelines are not a hugely important bit of data. Any breakage probably wouldn't be significant.

I wish I could remember why I went with CW. I do remember looking all over the place for existing (x,y)+angle guide implementations to reference, but I don't recall finding a lot of them. Maybe it was just FontLab and Inkscape? Anyway, what I did find was probably CW so I went with that.

**Comment by khaledhosny** [comment]
What about changing the guidelines to be just a regular layer? This is how FontForge handles it and I think it got that idea from FontGrapher. This has the advantage of supporting any arbitrary shape in the guidelines, and I have seen people put all sorts of shapes there.

**Comment by adrientetar** [comment]
> What about changing the guidelines to be just a regular layer?

You can already make a guideline layer, the point of guidelines is you know they are special lines, and you can e.g. show measurements at intersection with outlines or do special things like that. Or use the guidelines in scripting as they are named.

**Comment by benkiel** [comment]
@adrientetar hits the nail on the head. Guidelines are super useful for all sorts of things, from ease of scripting to accent placement. We're just debating how best to store the angle.

**Comment by khaledhosny** [comment]
So can I have a Guidelines layer with a single glyph that will be shown in all glyphs with the need to copy/sync it manually?

**Comment by jvgaultney** [comment]
Could this finally be changed in the spec to be CCW? Both Robofont 3 and Glyphs interpret the angle in a UFO3 to be CCW - in conflict with the published spec. So effectively the UFO3 spec *has* changed. Unfortunately other tools (glyphsLib in particular) still follow the published spec, which means that roundtripping fails. Changing the spec to reflect the practice of the major apps would be a great help.

**Comment by typesupply** [comment]
Okay, let's change the spec. I'm really busy at the moment, so it would be great if someone could:

1. triple check that RoboFont and Glyphs are doing this. (It's not that I don't believe anyone, I just want to be 1,000% certain. :)
2. Fork and update the text. Please add a "important corrections" section to the bottom of ufo3/index that notes that this change was made.
3. Submit a PR.

**THANKS!**

**Comment by jvgaultney** [comment]
i've confirmed (again) that Robofont and Glyphs interpret the values as CCW. i see that @moyogo had already changed it in his fork, so I'll leave it to him to finish it by adding an 'important corrections" note and submitting the PR. Thanks everyone!

**Comment by anthrotype** [comment]
> Unfortunately other tools (glyphsLib in particular) still follow the published spec

@jvgaultney could you please open an issue on glyphsLib repo about this? you're welcome to send a PR to fix this if you like, thanks!

**Comment by jvgaultney** [comment]
I was planning to do just that after the spec had been changed. Will do that now.

**Comment by typesupply** [comment]
The spec has been updated. Thanks everyone!
