### ISSUE TITLE
Tweak the kerning value resolution order.

### ISSUE THREAD

**Issue by typesupply** [unified-font-object/ufo-spec#27]
The UFO 3 spec currently defines that there must not be a conflict between glyph + group and group + glyph pairs. However, in practice we are seeing quite a few of these. Here is the issue that the specification tried to prevent. Given these two groups:

| name | members |
| --- | --- |
| public.kern1.O | O, D, Q |
| public.kern2.E | E, F |

Given these kerning pairs:

| Side 1 | Side 2 | Value |
| --- | --- | --- |
| public.kern1.O | public.kern2.E | -100 |
| public.kern1.O | F | -200 |
| Q | public.kern2.E | -250 |
| D | F | -300 |

Flattening all of these into glyph + glyph pairs results in this:

| Side 1 | Side 2 | Value |
| --- | --- | --- |
| O | E | -100 |
| O | F | -200 |
| D | E | -100 |
| D | F | -300 |
| Q | E | -250 |
| Q | F | **-200 or -250** |

The Q + F pair has two different values. This is unresolvable, so the spec explicitly forbids these conflicts.

@behdad had a [proposal](https://github.com/typesupply/defcon/issues/38#issue-143846142) for handling this with a spec tweak. The value resolution order would go from this:
1. glyph + glyph
2. glyph + group _or_ group + glyph
3. group + group

To this:
1. glyph + glyph
2. glyph + group
3. group + glyph
4. group + group

---

Here are the things that need to be changed within the UFO spec and ufoLib:
- [x] Remove or rewrite the "Exception Caveat" section.
- [x] Update the kerning value lookup algorithm.
- [x] Update the kerning value lookup sample implementation.
- [x] Update the kerning validator, probably removing it, in ufoLib.

**Comment by typesupply** [comment]
Turns out, the [example implementation already does this](https://github.com/unified-font-object/ufo-spec/blob/07256242e6e1545cef18174db26545aca93e9af9/source/versions/ufo3/kerning.html#L447). [So does the defined algorithm](https://github.com/unified-font-object/ufo-spec/blob/07256242e6e1545cef18174db26545aca93e9af9/source/versions/ufo3/kerning.html#L311).

**Comment by behdad** [comment]
Thanks @typesupply.  So, no spec changes needed after all? :)

**Comment by typesupply** [comment]
The algorithm implicitly did this but the spec explicitly forbid conflicting pairs. [I rewrote that section](http://unifiedfontobject.org/versions/ufo3/kerning.plist#exception-conflict-resolution).

I also took the opportunity (thanks to a massive reformatting by @typemytype) to switch the spec over to GitHub Pages so that changes like this are significantly easy to deploy. Yay!

**Comment by adrientetar** [comment]
> switch the spec over to GitHub Pages so that changes like this are significantly easy to deploy.

So the gh-pages branch, can you make that branch the default (in repository settings) and possibly delete the master branch to avoid any confusion?

**Comment by typesupply** [comment]
Yeah. I was waiting for the DNS propagation before I made a destructive change. Everything seems to be working now so I deleted master.
