### ISSUE TITLE
Add GLIF > lib > `public.postscriptName` to store the “production” glyph name

### ISSUE THREAD

**Issue by twardoch** [unified-font-object/ufo-spec#31]
Please add a GLIF > lib > `public.postscriptName` key intended to store the “production” glyph name that is intended to be stored in the `post` or `CFF` OpenType font tables. As per: 
- https://github.com/googlei18n/glyphs2ufo/issues/12
- https://groups.google.com/forum/#!topic/ufo-spec/pJnk5x1_6pE

**Comment by typesupply** [comment]
Got it. Thanks. I'll try to do this next week. Or, if you want to send me a PR I can review, merge and it'll be updated on unifiedfontobject.org within a minute or so after that.

**Comment by typesupply** [comment]
@twardoch I've been thinking about this. I think it would be better if the entries lived at the font's lib level as a mapping like this:

``` python
{
    "public.postscriptGlyphNames" : {
        "This A is awesome." : "A",
        "(" : "parentleft",
        # etc.
    }
}
```

This would let the data be shared across all layers. What do you think?

**Comment by twardoch** [comment]
I agree this is a much better method and makes more sense!

**Comment by brawer** [comment]
This seems resolved? http://unifiedfontobject.org/versions/ufo3/lib.plist/

**Comment by moyogo** [comment]
Same as #9. Resolved with font.lib `public.postscriptNames` key. Can be closed.

**Comment by anthrotype** [comment]
@typesupply can I and Denis get authorisation to close issues on this repo? thanks

**Comment by typesupply** [comment]
@anthrotype Check your access now. Email me if it isn't working.

**Comment by anthrotype** [comment]
it's working for me, thanks Tal!

**Comment by moyogo** [comment]
Thanks Cosimo and Tal!
