### ISSUE TITLE
Is 'layercontents.plist' required to have an entry for the default glyph layer?

### ISSUE THREAD

**Issue by readroberts** [unified-font-object/ufo-spec#38]
The spec is not entirely clear on whether or not the  'layercontents.plist' must have an entry for the default glyph layer. The spec does specify what the public name must be if the layer entry does exist, and the example of a 'layercontents.plist' file does show an entry for the default layer, but the wording can be read to suggest the an entry for the default layer is not required.

**Comment by typesupply** [comment]
Yes, it is required. I'll clarify the spec.

**Comment by anthrotype** [comment]
also somewhat related to this, if layercontents.plist "defines the order of the layers from top to bottom", and if the default layer is by definition the one that has "glyphs" directory name, isn't it always the case that the top-most layer in layercontents.plist, i.e. the "foreground" layer, is also always the default layer?

Shouldn't the spec be clearer about this point, and enforce this situation (default layer with "glyphs" directory is always the first in the layercontents array) -- which basically ratifies what every one is doing anyway?
What's the use of a "default" layer which is not at the top of all others?

**Comment by typesupply** [comment]
> also somewhat related to this, if layercontents.plist "defines the order of the layers from top to bottom", and if the default layer is by definition the one that has "glyphs" directory name, isn't it always the case that the top-most layer in layercontents.plist, i.e. the "foreground" layer, is also always the default layer?

I don't follow your logic here. Why does "glyphs" have to be the top most layer? I don't see that stated or implied in the spec at all.

> What's the use of a "default" layer which is not at the top of all others?

Think of a chromatic font that has three layers: the "main" shape, a "shadow" and a "highlight." The designer would likely have the order set to "highlight," "main," "shadow." As a designer, I'd think of "main" as the default layer.

**Comment by anthrotype** [comment]
thanks Tal for the clarification, now it makes sense. I guess I don't have a designer's mind :)
