### ISSUE TITLE
domain unifiedfontobject.org is expired?

### ISSUE THREAD

**Issue by steko** [unified-font-object/ufo-spec#39]
Hello, I followed the link to the UFO website from the Trufont home page, but I found a Gandi hosting courtesy page that tells me

> This domain name has been registered with Gandi.net
> 
> It is currently being parked by the owner

**Comment by typesupply** [comment]
It's still live: http://unifiedfontobject.org. We recently moved to a different host and I guess I forgot to set up the `www` subdomain. Thanks for letting us know!

**Comment by moyogo** [comment]
http://www.unifiedfontobject.org/ shows a page with "This domain name has been registered with Gandi.net".

**Comment by typesupply** [comment]
Ugh. Thanks for telling me. I’ll look into it.

**Comment by benkiel** [comment]
Fixed
