### ISSUE TITLE
PS hints in UFO

### ISSUE THREAD

**Issue by gferreira** [unified-font-object/ufo-spec#42]
- PS hints are not (yet) covered by the UFO specification
- there are at least 2 different implementations of PS hints in UFO (RoboFab/Superpolator, AFDKO/vfb2ufo)
- this creates interoperability problems, and ugly hacks to get things done

It seems a good idea to discuss this issue and agree on an official format for storing PS hints in UFOs.

I've collected some research findings [here](https://github.com/gferreira/PSHintsInUFO). Please feel free to correct, edit, expand.

**Comment by gferreira** [comment]
related: [Consider supporting Type 1 hints in GLIF](https://github.com/unified-font-object/ufo-spec/issues/5)

**Comment by gferreira** [comment]
see also: [UFO Specification Update #Hints (RoboThon 2015)](https://vimeo.com/123781570#t=7m35s)

**Comment by gferreira** [comment]
background: [discussion about Support for Type1 hints in UFO (2013)](https://groups.google.com/d/topic/ufo-spec/mRlcDYg6Shg/discussion)

**Comment by LettError** [comment]
The difference between the models is something to discuss. Do we need to store low level, exact representation of binary structures, or do we want to record a design decision and worry about the binary later. 

The data stored by the FDK autohinter is very detailed. It records everything that is necessary to make a working font, including tough problems like hint masks. 
This hint data expects the structure of the glyph to be immutable. It is invalidated with most edits. It also requires outlines to have their overlaps removed which means that interpolation of this kind of data is very difficult: point structures need not match between instances. 

The fontlab inspired _links_ are more flexible. These describe a connection between two points but do not really proscribe what that connection is. This type of data is easier to keep valid through edits. It can record an intention about a glyph such as "this is a stem" but not a full record of what FDK needs. 

Maybe now that overlaps will be allowed the autohinter might have to work differently.

**Comment by benkiel** [comment]
#53 should close this

**Comment by moyogo** [comment]
Resolved by #53.
