### ISSUE TITLE
Guideline x, y, and angle being None creates unknown states for scripting

### ISSUE THREAD

**Issue by benkiel** [unified-font-object/ufo-spec#47]
See the discussion in FontParts (https://github.com/robofab-developers/fontParts/issues/67). Would be better if the spec was changed so that None wasn't allowed for x, y, and angle.

**Comment by adrientetar** [comment]
All of x, y, and angle shouldn't be None if you ask me and angle should just default to 0. Otherwise you have to handle all the different (x, y, angle) possible cases in drawing/etc. code.

In TruFont I always set all three so I don't know if there's a need for some of these set to None?

**Comment by benkiel** [comment]
Going though open issues, should we make this change in the UFO spec?

**Comment by anthrotype** [comment]
possibly related https://github.com/unified-font-object/ufoNormalizer/pull/50

**Comment by belluzj** [comment]
As a general discussion for the meeting, I would argue that the UFO spec should in general choose to be prescriptive, especially on small details, to reduce the number of cases that need to be taken care of by implementers, and to facilitate diff-ability by having consistent serialization formats. In this particular case, the spec should force all fields to be present and have a meaningful value.

**Comment by schriftgestalt** [comment]
There are two different issues.
1) Writing zero values to the file (or to omit them to save space).
2) Having (zero) default values in the object model in memory.

The second is not really related to the ufo spec. More a problem with the font object mode. The reading code should set default values if a value is not present. And the writer checks if a value is the default and omit it.
