### ISSUE TITLE
Consider supporting Type 1 hints in GLIF.

### ISSUE THREAD

**Issue by typesupply** [unified-font-object/ufo-spec#5]
This is something that should probably make it into the spec. Things to consider:
- how does this impact existing parsers?
- can this be abstract enough to not require hard links to stem widths?

Read Roberts documented Adobe's private support for this in the FDK [here](https://groups.google.com/forum/#!topic/ufo-spec/7toFE5w9Y0g).

**Comment by moyogo** [comment]
#42 is a duplicate issue. We should close one and keep the other.
/cc @gferreira @typesupply

**Comment by benkiel** [comment]
#53 should close this

**Comment by moyogo** [comment]
Resolved by #53.
