### ISSUE TITLE
Clarify layercontents.plist is required or optional

### ISSUE THREAD

**Issue by mashabow** [unified-font-object/ufo-spec#51]
In [layercontents.plist](http://unifiedfontobject.org/versions/ufo3/layercontents.plist/), could you please add a sentence "This file is required." (e.g. [metainfo.plist](http://unifiedfontobject.org/versions/ufo3/metainfo.plist/)) or "This file is optional." (e.g. [fontinfo.plist](http://unifiedfontobject.org/versions/ufo3/fontinfo.plist/))?

**Comment by anthrotype** [comment]
it's definitely required in UFO3. Also, ufoLib would raise an exception if it's not there.

**Comment by benkiel** [comment]
Fixed by #72
