### ISSUE TITLE
Multiple masters?

### ISSUE THREAD

**Issue by madig** [unified-font-object/ufo-spec#52]
So nobody filed an issue on this yet it seems. How about support for multiple masters in a single UFO? The Glyphs file format could serve as an inspiration. The designspace file format could serve as the glue.

**Comment by moyogo** [comment]
See http://unifiedfontobject.org/roadmap/#unified-font-set

**Comment by davelab6** [comment]
@graphicore used UFO v3 layers in a similar way in Metapolator

**Comment by graphicore** [comment]
>  UFO v3 layers in […] in Metapolator

But it's not like that anymore. Basically all the data is now in in the UFO `data` directory.

**Comment by LettError** [comment]
The designspace file already serves as the glue. What more than "a folder of UFOs + designspace" do you need?

**Comment by madig** [comment]
@moyogo: Thanks, didn't see that one :)
@LettError: A well-specified container for an entire (style of a) family that contains all data that belongs together (feature files, groups, ...). Leaving this to segregated files, tools and specs only leads to chaotic tooling and interoperability bugs.
