### ISSUE TITLE
openTypeHeadCreated string does not specify timezone

### ISSUE THREAD

**Issue by anthrotype** [unified-font-object/ufo-spec#54]
The spec seems to imply that the openTypeHeadCreated date/time string should formatted with GMT time zone or UTC. A comment about the `head.created` field says

> created can be calculated by subtracting the 12:00 midnight, January 1, 1904 (as specified in the head table documentation) from the date stored at openTypeHeadCreated

I think this requirement should be made explicit, or maybe better the spec should allow to specify an additional time zone, e.g. +0800

**Comment by anthrotype** [comment]
@typesupply can we make it clear in the spec that all dates and times in the UFO should be interpreted as UTC instead of local time?

The lack of timezone information in the UFO date strings makes it ambiguous whether this represent Coordinated Universal Time or the local time when the UFO was created/modified.

If we want builds to be reproducible we need to make this explicit (e.g. see https://github.com/googlei18n/ufo2ft/pull/219)

We can simply say that all datetimes in UFO are UTC (i'm fine with that).
We can also allow the use of local datetimes with a `+HHMM` or `-HHMM` offset from UTC (like Glyphs.app does), but that's a bonus.

**Comment by typesupply** [comment]
I deferred to the OTF spec on this, but if you want to make it more explicit I'm fine with it. It always bothered me that it was ambiguous. If you submit a PR I'll review it and merge.

**Comment by anthrotype** [comment]
> I deferred to the OTF spec on this

Ok, so you did mean it to be interpreted as UTC. However, ufo2fdk (and hence ufo2ft) was interpreting it as local time - perhaps involuntarily?
It was using `time.mktime` which is the inverse of `time.localtime`, whereas it should be using `calendar.timegm`, the inverse of `time.gmtime` (UTC):

https://github.com/typesupply/ufo2fdk/blob/4cb942f3283435403d5753c42ebc99ab25abb9a5/Lib/ufo2fdk/fontInfoData.py#L623-L628

I'll send a PR.

**Comment by typesupply** [comment]
> Ok, so you did mean it to be interpreted as UTC. However, ufo2fdk (and hence ufo2ft) was interpreting it as local time - perhaps involuntarily?

Yeah, probably a mistake.
