### ISSUE TITLE
Add fontinfo information for OpenType meta table

### ISSUE THREAD

**Issue by moyogo** [unified-font-object/ufo-spec#56]
The [meta](https://docs.microsoft.com/en-us/typography/opentype/spec/meta) table was added to the OpenType spec in version 1.8 in September 2016, it was previously in the Apple TrueType specification.

The meta table information can probably be added, for example under the key `openTypeMeta`, as a dict with keys restricted to the registered tags `appl`, `bild`, `dlng`, and `slng` or private tags in all uppercase ASCII letters (however the [Apple TrueType spec](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6meta.html) says the first letter must be a capital letter), values can be either `<string>` or `<data>` elements. The values for `appl` and `bild` must be `<data>`, the values of `dlng` and `slng` must be `<string>` elements, all others should be allowed to be either.

It would be particularly useful to be able to define the `dlng` “Design languages” and `slng` “Supported languages” metadata in UFO.

**Comment by benkiel** [comment]
+1, do you have a chance to put together a PR?

**Comment by bobh0303** [comment]
A question:
>  the values of `dlng` and `slng` must be <string> elements

The OT spec says:
>The values for 'dlng' and 'slng' are comprised of a series of comma-separated ScriptLangTags, which are described in detail below. Spaces may follow the comma delimiters and are ignored.

which suggests that these two values are conceptually lists. Would it be useful to store these explicitly as lists within the UFO? Example:
```
    <key>dlng</key>
    <array>
        <string>script-lang1</string>
        <string>script-lang2</string>
    </array>
```

**Comment by moyogo** [comment]
I opened #60 to add the `public.openTypeMeta` with value as an array of strings for `dlng` and `slng`.
