### ISSUE TITLE
line metrics question

### ISSUE THREAD

**Issue by bobh0303** [unified-font-object/ufo-spec#63]
I understand that the fontinfo.plist fields 

- `openTypeHheaAscender`
- `openTypeHheaDescender`
- `openTypeHheaLineGap`
- `openTypeOS2TypoAscender` 
- `openTypeOS2TypoDescender` 
- `openTypeOS2TypoLineGap`
- `openTypeOS2WinAscent` 
- `openTypeOS2WinDescent` 

correspond directly with fields in the `hhea` and `OS/2` tables of an OpenType font.

How do the fontinfo.plist fields `ascender` and `descender` relate to the above? I don't see anything in the spec that suggests a relationship.

**Comment by typesupply** [comment]
Good question. Unfortunately, that's outside of the scope of the UFO. The UFO spec is an encapsulation format and is agnostic about what these kinds of specific values mean beyond what is stated in the originating spec. In this case, there are different recipes for calculating vertical metrics for different environments _(cough Microsoft Word cough)_ and, as far as I know, none of those have been deemed "right" or "official."

**Comment by benkiel** [comment]
Re-opening as some language in the spec saying that the UFO says nothing about this is likely helpful.
