### ISSUE TITLE
Keying sidebearings/widths?

### ISSUE THREAD

**Issue by madig** [unified-font-object/ufo-spec#69]
Since assigning other glyphs as a value to the sidebearings is so useful in Glyphs, I was wondering if it was within the scope of the UFO specification to add official support for that?

**Comment by LettError** [comment]
Would a public key for the glyph.lib be enough?

**Comment by madig** [comment]
I suppose.

Although I'd have to think of the format. Sometimes, you may want the left sidebearing of x plus 5 font units and things like that

@anthrotype @moyogo @belluzj: how to maximize the usefulness of this in the face of Glyphs?

**Comment by typesupply** [comment]
I've seen tools that can do much more than "n = h." I think this is a tool specific thing and is outside of the scope of the UFO. If a tool developer wants to share their data, they can publish their key and algorithm.

**Comment by typesupply** [comment]
I've seen tools that can do much more than "h = n." So, I think this is a tool specific thing and out of the scope of the UFO. If a tool developer wants to make their data public, they can publish their key and value formula.

**Comment by benkiel** [comment]
@madig Ok to close this?

**Comment by madig** [comment]
Yes.
