### ISSUE TITLE
Moving color keys out of .glif files?

### ISSUE THREAD

**Issue by madig** [unified-font-object/ufo-spec#70]
Our designers brought this up: we have multiple people in a team working on the same font/project in a different area and often, people get a lot of merge conflicts because of color differences.

A team leader in charge of the main development branch might color certain glyphs in a certain way to say e.g. "hands off, these are final". Every other person working on something then colors their glyphs and others they reference in a way that carries an arbitrary meaning to them; This can massively inflate the diff people have to look at before checking their stuff in and more often than anyone likes, colors slip through and you end up with a merge conflict.

I was thinking about how to make this more manageable.

- Strip all color information, always, before merging; UFOs outside topic branches are colorless. Doable, but what if the team lead wants certain glyphs to stay e.g. red to nudge people away from modifying them? And if you just strip a topic branch before merging, you'd overwrite the team-leader-colors on merging. Might be avoidable by a custom script that resets colors before merging, but that would be an additional step or we have to get people to use pre-commit, which is additional complexity.
- Move color information from the .glif files to a `lib` dictionary. Merge conflicts stay, but are more manageable (it's also easier to just not commit `lib.plist` when you only changed glyphs).
- Move color information into a separate `color.plist` that people simply do not commit (e.g. via `.gitignore`). Team lead can force-add the file to color something.
- Move color outside UFO/Git control and piggy-back it on our UFO-to-FontLab-or-Glyphs scripts. 

The last three options however present a problem: what if we want to use an editor one day that works directly on UFOs? Ideally, a solution becomes part of the specification.

So... any thoughts?

**Comment by madig** [comment]
Situations were color changes can happen:

- The designer forgets and changes color of something that doesn't "belong to him"...
- ... or applies some operation to a lot of things that happens to change color for too many things to keep track of what should be colored what. The resulting huge file diff can be overwhelming.
- Round-tripping between UFO, FontLab and Glyphs produces color changes because all of them use a different color model and the round-tripper has to deal with impedance mismatch.

**Comment by andyclymer** [comment]
If I could chime in — the color is an attribute of the glyph so it makes sense that the data stays with the glif file, but everyone has their own standards for how the colors are used. If the meaning of the color is important in your project then it sounds like you would still have a conflict whether the colors were stored in a separate file, one designer's arbitrary change of color would still result in a conflict with the team leader's choices.

The same problems would happen if a designer edits any other data in an area that "doesn't belong to them", a custom merge tool would still be needed.

I agree though that it does sound annoying if you're unable to get the same color when round-tripping between a UFO, FontLab and Glyphs, you're making a good case for a good "pre-commit" script to tidy up a designer's work into an agreed upon format, where all the mark colors (and anything else that wouldn't match) could be normalized...but I still don't know if it would help to move the data somewhere else.

**Comment by madig** [comment]
It indeed is partly (mostly?) a workflow problem. The above "mitigations" are one way to make the problem more manageable by reducing conflict area. I'm thinking about options before resorting to custom scripts/merge hooks. Those would be an additional burden and our less technically inclined colleagues struggle with Git as is...

**Comment by madig** [comment]
I actually improved glyphsLib's color handling, the code is in 2.3.1. We will also shortly deploy an improved UFO3-to-FontLab script internally that will hopefully cut down on rogue color changes... maybe this will be enough to satisfy everyone here.
