### ISSUE TITLE
Anchor: preserving semantics on what attaches where?

### ISSUE THREAD

**Issue by madig** [unified-font-object/ufo-spec#71]
I was wondering if the UFO spec was the right place to preserve the information how a composite is composited.

Glyphs allows once to specify what component should attach to which base glyph anchor and tools like [psfbuildcomp](https://github.com/silnrsi/pysilfont/blob/master/docs/composite.md) source the semantics from external files. UFOs currently store only the raw component references and positions...

**Comment by LettError** [comment]
You mean something like [GlyphConstruction](https://github.com/typemytype/GlyphConstruction)?

**Comment by madig** [comment]
Yes, but preserved in the UFOs.

**Comment by LettError** [comment]
Well, as there are multiple schemes on how to do this the spec is not the place to decide which is the best one. If you object to external files you can store any data you want in the ufo: either in the [font.lib](http://unifiedfontobject.org/versions/ufo3/lib.plist/) or in [ufo/data.](http://unifiedfontobject.org/versions/ufo3/data/)

**Comment by madig** [comment]
Well, the result of the construction could be stored, no? I.e. instead of (or in addition to)
```
	<outline>
		<component base="a"/>
		<component base="dieresiscomb" xOffset="258" yOffset="13"/>
	</outline>
```
You could write
```
	<outline>
		<component base="a"/>
		<component base="dieresiscomb" attachmentBaseGlyph="a" attachmentAnchorOwn="_top" attachmentAnchorBase="top" />
	</outline>
```

**Comment by jvgaultney** [comment]
I'd suggest that a UFO already contains a definition of glyph construction, using the component element and xOffset yOffset. If you then store an additional, separate definition in some higher level syntax than you will too easily get conflicts as one definition is changed and the other is not updated to match (and in some cases doing that updating may not be algorithmically possible). Which would be considered canonical? 

With our [syntax](https://github.com/silnrsi/pysilfont/blob/master/docs/composite.md) and [tool](https://github.com/silnrsi/pysilfont/blob/master/docs/scripts.md#psfbuildcomp) we tend to store a composites.txt file of definitions in the source of the project. We do the same with other sources that are better maintained outside the UFO.

**Comment by madig** [comment]
> I'd suggest that a UFO already contains a definition of glyph construction, using .

Using what? 😁

**Comment by jvgaultney** [comment]
Sorry - markdown fail - comment updated

**Comment by madig** [comment]
Hm. Does the UFO really contain the glyph construction definition? All it contains is which component goes where. How is an editor to know that moving the anchor in the base glyph should move the component in all composites, too? At least without additional non-standard metadata somewhere. You could of course run the script again, but... meh.

**Comment by gferreira** [comment]
there are other schemes for building composites which do not require anchors. for example, GlyphConstruction can use local and global guidelines, relative positioning, combining anchors/guides with an offset…

**Comment by madig** [comment]
Ah, good to know.

**Comment by jvgaultney** [comment]
The UFO contains a minimal, low-level definition of the composition. There are multiple higher-level methods of describing glyph composition, with different levels of abstraction. I like anchors, as that is the only one that seems to make design sense, but others like other methods.

The main problem with storing higher level glyph composition info alongside the standard glif definition is consistency and the great likelihood that the two defs would get out of sync. An editor would need to carefully modify *both*.

If you really wanted to store higher-level composition info in the UFO, there are two other ways to do it, provided you carefully defined the relationship between the low and high level definitions.

- Store a definition in a glif lib private key, although that then begins to cause problems when you start working in multiple layers.
- Store the definitions in the font lib.plist, as in:
``` plist
<key>public.glyphComposition</key>
<dict>
    <key>aacute</key>
    <string>a + acute</string>
    ...
</dict>
```
Similar arguments applied in discussion of _public.postscriptNames_ and why they are in lib.plist vs glif lib.

We've chosen to have our composite definitions in a separate file. It's more easily editable, and until there is a public.glyphComposition key _and editors that read and use it_ there is little compelling reason to have it in the UFO.

**Comment by typesupply** [comment]
Excellent summary, @jvgaultney. Thanks!
