### ISSUE TITLE
TrueType startpoint issues

### ISSUE THREAD

**Issue by jenskutilek** [unified-font-object/ufo-spec#74]
This came up while experimenting with TrueType hinting data in UFOs extracted from TTF files.

At the moment, the various Python tools go out of their way to make sure that contours start with an oncurve point, even though as far as I can see, the UFO spec does not require it. When converting a TTF to UFO, this results in start points being shifted around the contour, making extracted TrueType hinting data practically useless.

I can imagine two solutions:

* Relaxing the requirement that the first point in a contour is an oncurve point (Would require revision of all pen-based tools)
* Maintaining a reference to the original point index:
```<point x="433" y="371" type="move" ttindex="24" />```

Any thoughts on this issue?

**Comment by anthrotype** [comment]
Seems more like a tool issue than spec related.
Can you point to an example of such tools that make this assumption?

**Comment by anthrotype** [comment]
Ah I think you mean the adapter pens in ufoLib.pointPen.
Yea, when going between point-wise representation of a contour to a segment-oriented one and vice versa the original point index may get lost.
Maybe once we have fontTools.ufoLib, we can have the glyf table’s Glyph export a point pen interface (a drawPoints method that takes a point pen).

**Comment by jenskutilek** [comment]
Ah, yes, indeed, a point pen in glyf.Glyph would solve the problems as far as I can see (when tools like extractor will use it). I'll have a go at it.

**Comment by anthrotype** [comment]
@jenskutilek thanks! :+1:

**Comment by benkiel** [comment]
@jenskutilek Can this be closed?

**Comment by jenskutilek** [comment]
Yes, it has been fixed in FontTools.
