### ISSUE TITLE
Glyph, layer and other names need to exclude some characters.

### ISSUE THREAD

**Issue by typesupply** [unified-font-object/ufo-spec#80]
At the moment, the spec does not place any limitations on glyph, layer and (probably) other names can contain any character. This should be changed to exclude [control characters](https://en.wikipedia.org/wiki/ASCII#Control_characters).

**Comment by justvanrossum** [comment]
I was thinking about this. The UFO spec contains `features.fea`, and that has more strict limits on glyph and group names than UFO itself. In other words, once you use features.fea, there are implied glyph and group name limitations. Am I missing something?

**Comment by typesupply** [comment]
Correct, but the restrictions of the features.fea syntax don't percolate up to the UFO level. We don't require that the data in the UFO be 1:1 compatible with the data in features.fea.

**Comment by schriftgestalt** [comment]
What is the current recommendation of kerning class names? Is it OK to have hyphens?

**Comment by benkiel** [comment]
The rules for UFO3 are here: http://unifiedfontobject.org/versions/ufo3/groups.plist/, other than the prefix for kerning groups, group names can contain any character (so it's ok to have hyphens) in the UFO (though, this should likely, as noted above, remove control characters). Do note that what the UFO allows and what the FDK allows may be different (UFO is looser, as noted above)

**Comment by schriftgestalt** [comment]
I got so far. Just wanted to ask if anyone knows of a limitation in the current toolchain.

**Comment by benkiel** [comment]
@schriftgestalt Not from the UFO side, but you would want to check with the FDK and FontMake.

Looking here: http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#2.g.ii it's not clear if the naming restrictions are from final or production names (production allows for hyphen). My guess is that it's final, but best to ask over there.
