### ISSUE TITLE
Point().selected

### ISSUE THREAD

**Issue by BlackFoundry** [unified-font-object/ufo-spec#83]
Wouldn't it be nice / meaningful to have a (bool) flag to specify whether a Point is selected? I think that is one thing that is missing to directly make a simple UI on top of the UFO format. Might be useful to store the selection state of an object too (?)

**Comment by madig** [comment]
I'm still not so sure this maps nicely to the format, as the current flags for a point contribute to its interpretation, whereas a `selected` property is purely UI state.

Maybe you can find a way to use a glyph's `lib` dict to store the information? Something like, on selection, you assign an `identifier` to a point unless it already exists and use a lib key in the glyph like `com.black-foundry.trufont.selectedPoints` to hold a set of identifiers. A `selected()` property would do `return self.identifier in glyph.lib["com.black-foundry.trufont.selectedPoints"]` or something. You'd have to subclass `Point` of course.

**Comment by typesupply** [comment]
We will be adding a lib-like place to store interface data such as this as a public location in the data directory soon. See #121.
