### ISSUE TITLE
Glyph script (Writing system) and direction

### ISSUE THREAD

**Issue by typoman** [unified-font-object/ufo-spec#88]
Following from issue #87. There is a difference on how kerning pairs are stored in UFO and how OpenType GPOS value records are stored. Examples:

| Kerning Pair in UFO  | GPOS vlaue record |
| ------------- | ------------- |
| (`BIDI`, `BIDI`) | `-10` |
| (`LTR`, `LTR`) | `-20` |
| (`RTL`, `BIDI`) | `-30, 0, -30, 0` |
| (`RTL`, `RTL`) | `-40, 0, -40, 0` |

If a glyph doesn't have a Unicode we need explicit data to indicate its direction state while converting UFO kerning pairs to GPOS records and also deciding on lookup flags. If we don't come to a consensus on how it should be stored inside the UFO, compilers need to interpret the glyph name or other glyph data or maybe their own undisclosed data to define its direction and that's not reliable always. The direction of an entry from the kerning pair can only be one value from a set of defined values:

`RTL`: Right to Left
`LTR`: Left to Right
`BIDI`: Bi-directional or Neutral

Details on what algorithm should be used to add above values to glyph or on how to convert the kerning data to GPOS value records or how to add lookup flags could be discussed further if you agree on the premise.

**Comment by typoman** [comment]
Also to add, there is a possibility a PUA Unicode is used for a glyph and that should be overridden as the bidi algorithm should not decide on the direction of that Unicode.

**Comment by typoman** [comment]
Another way to solve this is by using a `script` tag for glyphs. If an entry from a kerning pair is from 'Arabic' or 'Hebrew' or any other RTL script then it should be recorded as 4 int array. An algorithm is not completely reliable also to retrieve the script tag for glyphs that has PUA or don't have Unicode so a user should be able to define this.

**Comment by typoman** [comment]
~~Another exception for `script` tag is that Arabic numbers are not supposed to be in similar lookup as the rest of Arabic letters. So `script` tag will not be sufficient.~~ see below!

**Comment by anthrotype** [comment]
> Arabic numbers are not supposed to be in similar lookup as the rest of Arabic letters.

https://github.com/googlefonts/ufo2ft/issues/198#issuecomment-358864155

**Comment by anthrotype** [comment]
(pressed green button too fast)

It's not true, one can perfectly have LTR kern pairs for digits in the same kerning lookup that also contains RTL kern pairs and that gets registered under RTL scripts. E.g., this is perfectly valid:

```
languagesystem DFLT dflt;
languagesystem arab dflt;

lookup kern_rtl {
    pos four-ar seven-ar -30;
    pos reh-ar.fina lam-ar.init <-80 0 -80 0>;
} kern_rtl;

feature kern {
    script arab;
    language dflt;
    lookup kern_rtl;
} kern;


```

**Comment by typoman** [comment]
Thank you @anthrotype. It works! But the lookup you mentioned is not sufficient as there needs to be `IgnoreMarks` flag on the lookup If there is no mark in any kerning pair inside the lookup. Since the problem is solved using the `script` tag I will change the title and what needs to be added to a glyph which is the `script` tag for cases Unicode is not available or it's PUA.

**Comment by schriftgestalt** [comment]
It still need to decide what value record format to use. `-30` vs `<-80 0 -80 0>`

**Comment by typoman** [comment]
Exactly, the value records are different. What if a glyph is related to numbers and it doesn't have Unicode?

**Comment by typoman** [comment]
Or a glyph related to Arabic numbers have PUA Unicode?

**Comment by typoman** [comment]
There is a need for `script` tag to put Arabic kerning pairs in one shared lookup and a `direction` tag to differentiate GPOS kerning value records for pairs that include an `RTL` glyph. ~~Also to avoid mixing any `RTL` and `LTR` glyphs in any lookup as they are invalid.~~ Avoid mixing any `RTL` and `LTR` glyphs in a class or a kerning pair as they are invalid.

**Comment by justvanrossum** [comment]
@typoman, after reading Cosimo's epic description, would you consider building your fonts with fontmake, at least to see how it affects your issue?

**Comment by typoman** [comment]
I think it's very clear how Cosimo explained and I will follow the same logic. I can summarize it like this:
Before writing any GPOS value record or lookups, first GSUB substitutions need to be established and also the CMAP. From that, anyone can obtain `script` and `direction` of the glyph using fontTools. Thank you all for taking your valuable time, this issue can be closed.

**Comment by typoman** [comment]
For future reference, the detailed explanation of Cosimo can be found here:
https://github.com/unified-font-object/ufo-spec/issues/16#issuecomment-488751554
