### ISSUE TITLE
Caret positions for ligatures

### ISSUE THREAD

**Issue by typoman** [unified-font-object/ufo-spec#89]
Following from issue #87. Sorry to keep posting these consecutively but you don't have to answer right away. Caret positions are used to indicate the start and end of components of a ligature when the typing cursor is moved on the ligature in text. Carets can be defined in two ways:
1. Adding anchors for caret positions. Example:
ligature width: 400
Final caret values in the binary: 120, 200, 330
Caret Anchors ~~for a `LTR` glyph~~: caret_1, x:120, y:any value, caret_2, x:200, y:any value, 
caret_3, x:330, y:any value
~~Caret Anchors for a `RTL` glyph: caret_1, x:280, y:any value, caret_2, x:200, y:any value, 
caret_3, x:70, y:any value~~
The implementations don't need to decide how to display the carets but they could be easily mixed with anchors used for mark positioning and glyph construction. ~~Name of the carets should have an int number to indicate the visual order of the caret for `RTL` or `LTR` glyph.~~ Extra unused anchor data is saved in the glyph. The compiler needs to differentiate between what is mark anchor and caret pos on compile. ~~The compiler needs to calculate caret values on compile.~~

2. Writing position of carets in glyph lib key as a fixed order array. Example:
ligature width: 400
Final caret values in the binary: 120, 200, 330
Caret value ~~if the glyph is `LTR`~~: 120, 200, 330
~~Caret value if the glyph is `RTL`: 330, 220, 120~~
The implementation could decide if any value in the array does not exceed the ligature width. ~~The order of array indicates how carets should be displayed in an interface where the user would add, change or modify them. If the order written in the array is descending the first caret should be displayed on the right of the glyph and the rest goes to the left and also the opposite if the order is ascending. The compiler doesn't need to calculate caret values on compile. The interface should calculate where carets should be displayed according to their order.~~

Number of ligature components = length of Carets + 1

This information later will be saved in the binary. One way of writing this is by using the adobe fea file:
http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#9b-gdef-table

**Comment by justvanrossum** [comment]
I like the first suggestion most. We can settle on a naming convention and that's that.

Perhaps `hcaret_X` for horizontal, and `vcaret_X` for vertical, where `X` is one or more decimal digits. If there's only one caret position (two ligature components), should the `_X` part be optional?

When you say "visual order", do you mean "visual left-to-right"?

**Comment by typoman** [comment]
Example of visual order:
ligature width: 400
Final caret values in the binary: 120, 200, 330
Caret Anchors for a ~~`LTR`~~ glyph: `caret_1`, x:120, y:any value, `caret_2`, x:200, y:any value,
`caret_3`, x:330, y:any value
~~Caret Anchors for a `RTL` glyph: `caret_1`, x:280, y:any value, `caret_2`, x:200, y:any value,
`caret_3`, x:70, y:any value~~

~~See the difference in x values? In an interface, if a user is looking at caret indices in `RTL` glyph, the index is ascending from right to left and for `LTR` glyph its the opposite.~~ My preference is the glyph lib key because it's cleaner.

**Comment by justvanrossum** [comment]
I would call that "logical order", but ok.

But perhaps it doesn't even matter. I think carets always go from left to right or from right to left, and I don't think [120, 330, 200] can mean anything useful.

Also note that [the spec](https://docs.microsoft.com/en-us/typography/opentype/spec/gdef#ligature-glyph-table) says "Array of offsets to CaretValue tables, from beginning of LigGlyph table — in increasing coordinate order".

I prefer the anchor solution because that gives it a UI right out of the box, at least in RF.

**Comment by justvanrossum** [comment]
Btw I don't see a flag for horizontal or vertical use in that GDEF subtable spec, they just talk about "X or Y value".

Perhaps it makes no sense for a ligature to have both horizontal and vertical caret positions defined? @moyogo, do you have any insights here?

**Comment by moyogo** [comment]
@justvanrossum X values are horizontal carets, Y values are vertical carets.

**Comment by moyogo** [comment]
Oh, I see what you mean, sorry. Yes, there’s maybe no need to make the distinction since it can be derived from the glyphs writing direction.

**Comment by anthrotype** [comment]
i'm curious if support for GDEF LigatureCarets is implemented anywhere. Last time I checked long time ago, I couldn't find any.

**Comment by typoman** [comment]
>  I don't think [120, 330, 200] can mean anything useful.

That could easily be said for anchors too as the user has control over their position.

> Perhaps it makes no sense for a ligature to have both horizontal and vertical caret positions defined?

That's the reason for the glyph lib and why it's cleaner.

**Comment by typoman** [comment]
> I'm curious if support for GDEF LigatureCarets is implemented anywhere.

@schriftgestalt has implemented them. I wonder if there was a request that carets are not displayed right in a text editor.

**Comment by anthrotype** [comment]
yes, I meant implemented in a real-world layout engine.

**Comment by justvanrossum** [comment]
> > I don't think [120, 330, 200] can mean anything useful.

> That could easily be said for anchors too as the user has control over their position.

I actually meant that in that context. We were talking about the X in `caret_X`, and how that X relates to the writing direction. I'm arguing that we don't need any definition that talks about writing direction vs. caret order, because:

1. The caret positions need to get sorted one way or another anyway
2. GDEF specifies them to be sorted by increasing coordinate value anyway

> > Perhaps it makes no sense for a ligature to have both horizontal and vertical caret positions defined?

> That's the reason for the glyph lib and why it's cleaner.

I don't understand how that follows, but ok.

There's a precedent in using meaningfully named anchors for feature generation: the various Mark features can be generated using anchors. Glyphs does it that way, and fontmake does it this way via ufo2ft's `MarkFeatureWriter` class.

**Comment by typoman** [comment]
~~The direction in storage is not important but for the user in the interface, it's needed to create the data. Ascending and descending order can indicate that but it's not an obligation for implementation to impose that. Unless the direction of a glyph is obtained otherwise, but for that, GSUB and CMAP need to be interpreted.~~ Is that idea appealing to write GSUB in the glyph lib (e.g: ligature components, the context of the substitution)? It can help a lot with feature generation and restricts the OT data to smaller bits of the font.

**Comment by justvanrossum** [comment]
> The direction in storage is not important but for the user in the interface, it's needed to create the data. 

Why?

**Comment by schriftgestalt** [comment]
As far as I know, Textedit (and potentially with it other Apple apps) does support ligature carets.

**Comment by typoman** [comment]
> > The direction in storage is not important but for the user in the interface, it's needed to create the data.
> 
> Why?

~~If the direction of a glyph is `RTL` the first caret should be displayed on the right of the glyph and the rest goes to the left. The opposite if the glyph is `LTR`.
Example:
ligature width: 400
Final caret values in the binary: 120, 200, 330
The glyph is `RTL`, caret positions in a similar order in glyph coordinates: 280, 200, 70
The glyph is `LTR`, caret positions in a similar order in glyph coordinates: 120, 200, 330~~

I'm explaining what I've said in the first comment over and over. It's all covered there.

**Comment by justvanrossum** [comment]
> I'm explaining what I've said in the first comment over and over. It's all covered there.

"I've explained why it doesn't matter in my comments above, it's all covered there."

Cut it with the attitude, @typoman, let's have a constructive discussion.

I'm may be missing something, but I understand caret positions to be X coordinates (let's ignore vertical for now) in the coordinate space of the glyph at hand. Something like this:

![image](https://user-images.githubusercontent.com/4246121/57136588-8fbfeb00-6dad-11e9-88aa-cdf0a4a8fd10.png)

How, for the designer drawing and defining this, is the writing direction and the order of those carets of any significance? How will the above be any different for a RTL glyph? How can I even tell the order in which it's displayed? What do you want to do with the order in this context?

**Comment by typoman** [comment]
I don't see any indication of attitude in my comments and I think I've explained all needed to be shown. I will not repeat myself.

**Comment by anthrotype** [comment]
I think he wants to be able to count the carets in a RTL ligature glyph starting from the right-most, i.e. in decreasing coordinate value. 
So in a 3-glyph RTL ligature, the "first" caret is the last in ascending coordinate value, i.e. the one between the "first" and "second" glyph (in logical order).

**Comment by anthrotype** [comment]
I think in the end the name of the anchors should not really matter (it only ensures the name is unique, which in UFO is not even a requirement, is it?), given that the CaretValues will have to be encoded in ascending coordinate order anyway in the GDEF.

**Comment by justvanrossum** [comment]
> I don't see any indication of attitude in my comments and I think I've explained all needed to be shown. I will not repeat myself.

Then I won't either, and I will no longer help you getting something like this into the spec.

**Comment by typoman** [comment]
I don't want to force into spec at all and I'm very grateful for your help here and I'm sorry if my comment looks like I have an attitude. The only reason I'm commenting here is to have an open discussion, even if it doesn't make it to the spec I think the information exchanged here will help many.

**Comment by justvanrossum** [comment]
I'll try one more time, but it's really tiresome.

> Name of the carets should have an int number to indicate the visual order of the caret for RTL or LTR glyph.

Why should that int number indicate the (logical) order of the caret?

> The interface should calculate where carets should be displayed according to their order.

What does that mean? Their _value_ (coordinate, horizontal position) determines where they should be displayed. It's just a coordinate overlaying the ligature glyph. What am I missing? Which interface?

What I mean by your attitude is that you suggest that I haven't read your comments properly. Well, I have, and I still don't follow you, and that's why I'm asking questions. Your refusal to elaborate comes across as rather aggressive.

**Comment by typoman** [comment]
Sorry, I was trying to avoid spending time to create an image that would illustrate the issue but if this comment doesn't clear it I will make the image. I think the confusion stems from the fact that the coordinate system in glyph starts on the left of the glyph no matter if the glyph is `RTL` or `LTR`. ~~But carets are not overlayed on the glyph, the layout engine (or any interface) should read carets in a logical order and should add them from starting point of the glyph. The visual starting point of an `RTL` glyph is on the right of the glyph but carets are written based on the glyph coordinates system which starts from the left of the glyph. So the layout engine or any interface should know the direction of the glyph in order to calculate the right position because the starting point is different visually. So in an `RTL` glyph if the first caret is written as 120 and width of the glyph is 400, in the glyph coordinate system, it should not be displayed at x=120 but at x=400-120.~~

**Comment by typoman** [comment]
~~Sorry, one mistake carets are written based on the visual coordinates system.~~

**Comment by justvanrossum** [comment]
So the `x=400-120` example is wrong?

**Comment by anthrotype** [comment]
The origin of a glyph’s coordinate system is always in the bottom left, no matter the writing direction.

**Comment by anthrotype** [comment]
Coordinates are in design units and caret values in GDEF are sorted in increasing coordinate order, there is no place for the logical writing direction order in this context. If you want to call your anchors with indices starting from the right it won’t change the end result.

**Comment by benkiel** [comment]
> If the direction of a glyph is RTL the first caret should be displayed on the right of the glyph and the rest goes to the left. The opposite if the glyph is LTR.

I think the confusion here is between storing values (UFO) and what a layout engine does (not UFO). The display of the caret is a layout engine problem, and the spec for caret states that the values are stored in ascending order, it's up to the layout engine to know the text direction and show the correct first caret.

I agree with @justvanrossum, we can specify that anchors with the name `caret` gives the position for the caret. If it's horizontal, the anchor y value should be 0, and the x value is the location. If vertical, then anchor x should be 0 and anchor y is the value. Any caret anchor with both x and y being non zero is invalid.

**Comment by justvanrossum** [comment]
> If vertical, then anchor x should be 0 and anchor y is the value. Any caret anchor with both x and y being non zero is invalid.

Not sure, this gives an ambiguity at (0, 0).

I would suggest the following:
- if the anchor is named `hcaret[_X]`, take the X coordinate and ignore the Y
- if the anchor is named `vcaret[_X]`, take the Y coordinate and ignore the X.

`hcaret` and `vcaret` may not occur simultaneously in a single glyph.

**Comment by benkiel** [comment]
@justvanrossum Ah, yes, you're right about (0,0). Yes, makes sense. Do we even need the `_X` as the order is just ascending

**Comment by justvanrossum** [comment]
> Do we even need the _X as the order is just ascending

 We don't, but I wouldn't mind to allow it, if users want to have distinct names for their own purposes.

**Comment by benkiel** [comment]
@justvanrossum Agree, makes sense.

**Comment by schriftgestalt** [comment]
I just tried the carter in MacOS. In RTL context, it moves the cursor in visual direction. So hitting the right arrow key, the cursor moves right, same as for LTR. Whereas in Indesign hitting the right arrow key, the cursor moves to the next character witch is visually to the left. So the layout engine has to calculate caret direction according to how it treat the cursor direction.

**Comment by schriftgestalt** [comment]
And in Glyphs, anchors have to be unique. What would be a use case of duplicate anchors other than the carets?

**Comment by justvanrossum** [comment]
From the UFO spec for anchor name: "An arbitrary name for the anchor. This attribute is optional."

**Comment by typoman** [comment]
I apologize if I caused any confusions, this is a complicated matter. Please ignore my comments as there are mistakes there. I will cross some of them. Here is what I found:
1. Order of carets in the fea file didn't affect their position in Mac TextEditor.app. So makeOtf fixed their order in the binary to ascending. TextEditor.app needs their carets as ascending otherwise it will not be able to read them correctly. Order of caret anchors should not matter in the source font at all as long as the font compiler is aware of making them ascending.
2. InDesign did not read the caret positions on ligatures and ignored it.
3. Caret positions should be written as exactly as they're written in the glyph coordinates no matter the direction of the glyph (`RTL`, `LTR`) for TextEditor.app (ergo CoreText) to read them correctly.

I will try to do more test before commenting next time. Thank you!

**Comment by justvanrossum** [comment]
Well, it was pretty simple until you made it complicated :)

**Comment by typoman** [comment]
One note for developers who want to implement the ligature caret position. This could become confusing if ligature is **Right to Left**. This is based only on how TextEdit reads the carets on ligatures and nothing else. The ligature glyph is splitted according to caret positions on glyph coordinates, then the first character is at the right of the glyph in an `RTL` ligature, obviously! I guess this is what made it complicated for me as I thought the caret order written in the binary is same as typing order (like kerning pair order).

**Comment by typoman** [comment]
I agree with any solutions you choose for a convention for carets. Both glyph lib or anchors works I think. I just preferred the glyph lib because it didn't get mixed with other anchors as they are mostly used for mark positioning in the glyph view and it could be annoying to have many anchors in the view which for Arabic ligatures could become a lot. Also, less process is needed to add them form glyph lib directly to the binary (no need to check anchor names, anchor y coordinates is also unused). One way to add them for ufo2ft could be to parse the GDEF and determine if there are any `LigCaretList` there or not. It could then read any anchors on glyphs that start with name caret and add them to the `LigCaretList` or define them anyway it could in the binary. It doesn't matter if caret names have an index or not.

**Comment by anthrotype** [comment]
why parse GDEF? It doesn't exist yet. The whole point of this is to have the feature writer generate these GDEF LigatureCaretByPos (as in Adobe FEA syntax) statements using such anchors (or guidelines) in the glifs.

**Comment by typoman** [comment]
Because it's possible that someone might have written LigatureCaretByPos in the fea file. But I guess you can override them?

**Comment by anthrotype** [comment]
This is a discussion we should have in the implementation side, but I think the compiler should default to skip adding LigatureCaretByPos if they are already written in the features.fea.

**Comment by benkiel** [comment]
This is what is done for kerning, already, so there is precedence there.

**Comment by benkiel** [comment]
Fixed by #90
