### ISSUE TITLE
Add glyph.lib registry entry for output name.

### ISSUE THREAD

**Issue by typesupply** [unified-font-object/ufo-spec#9]
See this discussion: https://groups.google.com/forum/#!topic/ufo-spec/pJnk5x1_6pE

**Comment by brawer** [comment]
Seems resolved? http://unifiedfontobject.org/versions/ufo3/lib.plist/

**Comment by moyogo** [comment]
Resolved with font.lib `public.postscriptNames` key. This can be closed.
