### ISSUE TITLE
Group name detection in convert UFO2 to UFO3 kerning sample implementation

### ISSUE THREAD

**Issue by jenskutilek** [unified-font-object/ufo-spec#98]
I ran into a bug with the [UFO2 to UFO3 kerning conversion sample implementation](http://unifiedfontobject.org/versions/ufo3/kerning.plist/#sample-conversion-implementation).

I am trying to build a font from a UFO generated by `vfb2ufo`. I need to do some preprocessing before building the font with `fontmake`/`ufo2ft` regarding glyph groups. The UFO from `vfb2ufo` is a UFO2, which will automatically be upgraded to UFO3 when opened with `defcon`. Now defcon uses the `UFOReader` from `fontTools.ufolib` to open the UFO.

Bear with me, I’m getting there. `defcon` is basically using the sample implementation for upgrading the kerning. But my UFO contains glyph groups with names that look like glyph names, e.g.

```
five: five, five.osf, five.tf, five.tosf
```

The implementation collects kerning group names from `kerning.items()`, where it will find a reference to `five`. But that `five` is a glyph name, not a kerning group name. The implementation doesn't know that, and assigns a prefix `public.kern1.` to five, thus generating a duplicate kerning group reference for `five`. The kerning/groups are broken now and fail validation in UFOReader...

I'm not sure how to solve this. Of course all my kerning groups are prefixed with `@MMK_`, so I wouldn't need to collect group names from the kerning items, but to only look for prefixes wouldn't work universally (though probably for 99% of existing UFO2 packages). Changing all group names in my existing files to be different from glyph names is also not an option, and AFAIK not required by the UFO spec.

**Comment by justvanrossum** [comment]
I think that `convertUFO1OrUFO2KerningToUFO3Kerning()` should do something like:

```python
if name in groups and not name in glyphNames:
    ...ok, name is a group name...
```

In other words it should check whether the name exists in the glyph set, in which case it can't be a group name.
